Resources:
  ListsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
Outputs:
  ListsTable:
    Value: !Ref ListsTable
  ListsTableArn:
    Value: !GetAtt ListsTable.Arn
